In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns
import cv2
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
df = pd.read_csv('/content/drive/MyDrive/monkeytype/mt_dataset_catm_b01.csv')
df.info()
df0 = pd.read_csv('/content/drive/MyDrive/monkeytype/monkeytyping.csv')
df0.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4675 entries, 0 to 4674
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   participant_id        4675 non-null   object
 1   brightness0           4675 non-null   float64
 2   brightness1           4675 non-null   float64
 3   brightness2           4675 non-null   float64
 4   brightness3           4675 non-null   float64
 5   local_symbol_cls0     4675 non-null   object
 6   local_symbol_cls1     4675 non-null   object
 7   local_symbol_cls2     4675 non-null   object
 8   local_symbol_cls3     4675 non-null   object
 9   correct_symbol_cls    4675 non-null   object
 10  correct_local_cls     4675 non-null   int64
 11  participant_linspace  4675 non-null   float64
 12  time_reaction_task    4675 non-null   int64
 13  time_reaction_mean    4675 non-null   float64
 14  chosen_local_cls      4675 non-null   int64
dtypes: float64(6), int64(3), object(6)
memory usage: 548.0+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6159 entries, 0 to 6158
Data columns (total 31 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   participant_id             6159 non-null   object
 1   date                       6159 non-null   object
 2   original_filename          6159 non-null   object
 3   trial_number               6159 non-null   int64
 4   reaction_time              6159 non-null   object
 5   correct                    6159 non-null   int64
 6   correct_position           6159 non-null   object
 7   chosen_position            6159 non-null   object
 8   prompt                     0 non-null      float64
 9   sample_name                0 non-null      float64
 10  file_1_name                6159 non-null   object
 11  file_2_name                6159 non-null   object
 12  file_3_name                6139 non-null   object
 13  file_4_name                6139 non-null   object
 14  colour_1_stimul            800 non-null    object
 15  colour_2_stimul            800 non-null    object
 16  colour_3_stimul            800 non-null    object
 17  colour_4_stimul            800 non-null    object
 18  date_parsed                6159 non-null   object
 19  participant_id_original    6159 non-null   object
 20  participant_id_normalized  6159 non-null   object
 21  file_path                  6159 non-null   object
 22  stimuli_quantity           6159 non-null   float64
 23  colored                    800 non-null    object
 24  nut_quantity               6159 non-null   float64
 25  juice_quantity             6159 non-null   float64
 26  datetime                   6159 non-null   object
 27  mean_reaction_time         6159 non-null   float64
 28  percent_correct            6159 non-null   float64
 29  omission_percent           6159 non-null   float64
 30  experiment_duration        6159 non-null   object
dtypes: float64(8), int64(2), object(21)
memory usage: 1.5+ MB

In [3]:
latent_dim = 16

feature_names_x1 = [f"x1_f{i}" for i in range(latent_dim)]
feature_names_x2 = [f"x2_f{i}" for i in range(latent_dim)]
feature_names_x3 = [f"x3_f{i}" for i in range(latent_dim)]
feature_names_x4 = [f"x4_f{i}" for i in range(latent_dim)]

In [4]:
dataset_columns1 = ['x1_linspace', 'x1_brightness', 'x1_time_reaction',
                    'x1_symbol_m', 'x1_symbol_c', 'x1_symbol_s', 'x1_symbol_y', 'x1_symbol_f', 'x1_symbol_j',
                    'x1_location_0', 'x1_location_1', 'x1_location_2', 'x1_location_3',
                    'x1_participant_J','x1_participant_F','x1_participant_Y',
                    'x1_correct_symbol_m', 'x1_correct_symbol_c', 'x1_correct_symbol_s', 'x1_correct_symbol_y', 'x1_correct_symbol_f', 'x1_correct_symbol_j',
                    'x2_linspace','x2_brightness', 'x2_time_reaction',
                    'x2_symbol_m', 'x2_symbol_c', 'x2_symbol_s', 'x2_symbol_y', 'x2_symbol_f', 'x2_symbol_j',
                    'x2_location_0', 'x2_location_1', 'x2_location_2', 'x2_location_3',
                    'x2_participant_J','x2_participant_F','x2_participant_Y',
                    'x2_correct_symbol_m', 'x2_correct_symbol_c', 'x2_correct_symbol_s', 'x2_correct_symbol_y', 'x2_correct_symbol_f', 'x2_correct_symbol_j',
                    'x3_linspace','x3_brightness','x3_time_reaction',
                    'x3_symbol_m', 'x3_symbol_c', 'x3_symbol_s', 'x3_symbol_y', 'x3_symbol_f', 'x3_symbol_j',
                    'x3_location_0', 'x3_location_1', 'x3_location_2', 'x3_location_3',
                    'x3_participant_J','x3_participant_F','x3_participant_Y',
                    'x3_correct_symbol_m', 'x3_correct_symbol_c', 'x3_correct_symbol_s', 'x3_correct_symbol_y', 'x3_correct_symbol_f', 'x3_correct_symbol_j',
                    'x4_linspace','x4_brightness','x4_time_reaction',
                    'x4_symbol_m', 'x4_symbol_c', 'x4_symbol_s', 'x4_symbol_y', 'x4_symbol_f', 'x4_symbol_j',
                    'x4_location_0', 'x4_location_1', 'x4_location_2', 'x4_location_3',
                    'x4_participant_J','x4_participant_F','x4_participant_Y',
                    'x4_correct_symbol_m', 'x4_correct_symbol_c', 'x4_correct_symbol_s', 'x4_correct_symbol_y', 'x4_correct_symbol_f', 'x4_correct_symbol_j',
                    'x1_linspace_session_id', 'x1_linspace_within_session',
                    'x2_linspace_session_id', 'x2_linspace_within_session',
                    'x3_linspace_session_id', 'x3_linspace_within_session',
                    'x4_linspace_session_id', 'x4_linspace_within_session',
                    'x1_omission_percent', 'x2_omission_percent', 'x3_omission_percent', 'x4_omission_percent',
                    'x1_correct_target', 'x2_correct_target', 'x3_correct_target', 'x4_correct_target',
]
dataset_columns1.extend(feature_names_x1)
dataset_columns1.extend(feature_names_x2)
dataset_columns1.extend(feature_names_x3)
dataset_columns1.extend(feature_names_x4)
df_dataset1 = pd.DataFrame(columns = dataset_columns1)
df_dataset1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Columns: 168 entries, x1_linspace to x4_f15
dtypes: object(168)
memory usage: 132.0+ bytes

In [5]:
brightness_list = ['brightness0',	'brightness1',	'brightness2',	'brightness3']
local_smb_list = ['local_symbol_cls0',	'local_symbol_cls1',	'local_symbol_cls2',	'local_symbol_cls3']
x1_symbol_list = ['x1_symbol_m', 'x1_symbol_c', 'x1_symbol_s', 'x1_symbol_y', 'x1_symbol_f', 'x1_symbol_j']
x1_correct_symbol_list = ['x1_correct_symbol_m', 'x1_correct_symbol_c', 'x1_correct_symbol_s', 'x1_correct_symbol_y', 'x1_correct_symbol_f', 'x1_correct_symbol_j']
x234_symbol_list = ['symbol_m', 'symbol_c', 'symbol_s', 'symbol_y', 'symbol_f', 'symbol_j']
x234_correct_symbol_list = ['correct_symbol_m', 'correct_symbol_c', 'correct_symbol_s', 'correct_symbol_y', 'correct_symbol_f', 'correct_symbol_j']
x1_location_list = ['x1_location_0', 'x1_location_1', 'x1_location_2', 'x1_location_3' ]
x234_location_list = ['location_0', 'location_1', 'location_2', 'location_3']
x1_participant_list = ['x1_participant_J','x1_participant_F','x1_participant_Y',]
x234_participant_list = ['participant_J','participant_F','participant_Y']
symbols_list = ['m', 'c', 's', 'y', 'f', 'j']

In [6]:
idx=0
for index, row in df.iterrows():
  x1_participant = row['participant_id']
  x1_location = row['chosen_local_cls']
  x1_linspace = row['participant_linspace']
  x1_correct_symbol = row['correct_symbol_cls']
  x1_time_reaction = row['time_reaction_task']
  for b, l in zip(brightness_list , local_smb_list):
    if str(x1_location) in b:
      x1_brightness = row[b]
      x1_symbol = row[l]
  df_dataset1.loc[idx,'x1_linspace'] = x1_linspace
  df_dataset1.loc[idx,'x1_brightness'] = x1_brightness
  df_dataset1.loc[idx,'x1_time_reaction'] = x1_time_reaction
  for sym_col in x1_symbol_list:
    if x1_symbol == sym_col[-1]:
      df_dataset1.loc[idx,sym_col] = 1.0
    else:
      df_dataset1.loc[idx,sym_col] = 0.0
  for loc_col in x1_location_list:
    if str(x1_location) == loc_col[-1]:
      df_dataset1.loc[idx,loc_col] = 1.0
    else:
      df_dataset1.loc[idx,loc_col] = 0.0
  for par_col in x1_participant_list:
    if x1_participant[0] == par_col[-1]:
      df_dataset1.loc[idx,par_col] = 1.0
    else:
      df_dataset1.loc[idx,par_col] = 0.0
  for sym_corr_col in x1_correct_symbol_list:
    if x1_correct_symbol == sym_corr_col[-1]:
      df_dataset1.loc[idx,sym_corr_col] = 1.0
    else:
      df_dataset1.loc[idx,sym_corr_col] = 0.0
  idx += 1

df_dataset1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4675 entries, 0 to 4674
Columns: 168 entries, x1_linspace to x4_f15
dtypes: object(168)
memory usage: 6.2+ MB

In [7]:
idx=0
for index, row in df.iterrows():
  x2_participant = row['participant_id']
  x2_linspace = row['participant_linspace']
  x1_location = row['chosen_local_cls']
  x2_correct_symbol = row['correct_symbol_cls']
  x2_time_reaction = row['time_reaction_task']
  x2_brightness = []
  x2_symbol = []
  x2_location = []
  for b, l in zip(brightness_list , local_smb_list):
    if str(x1_location) not in b:
      x2_brightness.append(row[b])
      x2_symbol.append(row[l])
      x2_location.append(b[-1])
  for i in range(3):
    x234_linspace = f"x{i+2}_linspace"
    df_dataset1.loc[idx, x234_linspace] = x2_linspace
    x234_brightness = f"x{i+2}_brightness"
    df_dataset1.loc[idx, x234_brightness] = x2_brightness[i]
    x234_time_reaction = f"x{i+2}_time_reaction"
    df_dataset1.loc[idx, x234_time_reaction] = x2_time_reaction

    x234_cols_symbols = [f"x{i+2}_{c}" for c in x234_symbol_list]
    for sym_col in x234_cols_symbols:
      if x2_symbol[i] == sym_col[-1]:
        df_dataset1.loc[idx,sym_col] = 1.0
      else:
        df_dataset1.loc[idx,sym_col] = 0.0
    x234_cols_location = [f"x{i+2}_{c}" for c in x234_location_list]
    for loc_col in x234_cols_location:
      if x2_location[i] == loc_col[-1]:
        df_dataset1.loc[idx,loc_col] = 1.0
      else:
        df_dataset1.loc[idx,loc_col] = 0.0
    x234_cols_participant = [f"x{i+2}_{c}" for c in x234_participant_list]
    for par_col in x234_cols_participant:
      if x2_participant[0] == par_col[-1]:
        df_dataset1.loc[idx,par_col] = 1.0
      else:
        df_dataset1.loc[idx,par_col] = 0.0
    x234_cols_corr_symbols = [f"x{i+2}_{c}" for c in x234_correct_symbol_list]
    for sym_corr_col in x234_cols_corr_symbols:
      if x2_correct_symbol == sym_corr_col[-1]:
        df_dataset1.loc[idx,sym_corr_col] = 1.0
      else:
        df_dataset1.loc[idx,sym_corr_col] = 0.0
  idx += 1

df_dataset1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4675 entries, 0 to 4674
Columns: 168 entries, x1_linspace to x4_f15
dtypes: object(168)
memory usage: 6.2+ MB

In [8]:
df_symbols = df0[df0['colored'].isna()].copy(deep=True)
df_symbols = df_symbols[df_symbols['file_3_name'].notna()].copy(deep=True)

In [9]:
df_symbols["session_id"] = (
    df_symbols["trial_number"].eq(1)
    .groupby(df_symbols["participant_id"])
    .cumsum()
    .sub(1)
)
# нормализация отдельно для каждого participant_id
mx = df_symbols.groupby("participant_id")["session_id"].transform("max")
df_symbols["session_id_norm"] = np.where(mx > 0, df_symbols["session_id"] / mx, 0.0)

max_trial = df_symbols.groupby(["participant_id", "session_id"])["trial_number"].transform("max")
den = max_trial - 1
df_symbols["trial_norm"] = np.where(
    den > 0,
    (df_symbols["trial_number"] - 1) / den,
    0.0
)

df_symbols.head(20)

,participant_id,date,original_filename,trial_number,reaction_time,correct,correct_position,chosen_position,prompt,sample_name,...,nut_quantity,juice_quantity,datetime,mean_reaction_time,percent_correct,omission_percent,experiment_duration,session_id,session_id_norm,trial_norm
0,Jupiter,02.06.2025,02.06.2025 - Jupiter.txt,1,1029,0,2th,3th,NaN,NaN,...,1.0,0.0,02.06.2025 11:59:45,980.0,35.0,4.0,"9 min, 35 sec",0,0.0,0.000000
1,Jupiter,02.06.2025,02.06.2025 - Jupiter.txt,2,579,1,2th,2th,NaN,NaN,...,1.0,0.0,02.06.2025 11:59:45,980.0,35.0,4.0,"9 min, 35 sec",0,0.0,0.020408
2,Jupiter,02.06.2025,02.06.2025 - Jupiter.txt,3,688,0,3th,4th,NaN,NaN,...,1.0,0.0,02.06.2025 11:59:45,980.0,35.0,4.0,"9 min, 35 sec",0,0.0,0.040816
3,Jupiter,02.06.2025,02.06.2025 - Jupiter.txt,4,578,0,4th,2th,NaN,NaN,...,1.0,0.0,02.06.2025 11:59:45,980.0,35.0,4.0,"9 min, 35 sec",0,0.0,0.061224
4,Jupiter,02.06.2025,02.06.2025 - Jupiter.txt,5,848,1,4th,4th,NaN,NaN,...,1.0,0.0,02.06.2025 11:59:45,980.0,35.0,4.0,"9 min, 35 sec",0,0.0,0.081633
5,Jupiter,02.06.2025,02.06.2025 - Jupiter.txt,6,793,1,1th,1th,NaN,NaN,...,1.0,0.0,02.06.2025 11:59:45,980.0,35.0,4.0,"9 min, 35 sec",0,0.0,0.102041
6,Jupiter,02.06.2025,02.06.2025 - Jupiter.txt,7,628,1,1th,1th,NaN,NaN,...,1.0,0.0,02.06.2025 11:59:45,980.0,35.0,4.0,"9 min, 35 sec",0,0.0,0.122449
7,Jupiter,02.06.2025,02.06.2025 - Jupiter.txt,8,771,0,2th,4th,NaN,NaN,...,1.0,0.0,02.06.2025 11:59:45,980.0,35.0,4.0,"9 min, 35 sec",0,0.0,0.142857
8,Jupiter,02.06.2025,02.06.2025 - Jupiter.txt,9,875,0,1th,3th,NaN,NaN,...,1.0,0.0,02.06.2025 11:59:45,980.0,35.0,4.0,"9 min, 35 sec",0,0.0,0.163265
9,Jupiter,02.06.2025,02.06.2025 - Jupiter.txt,10,662,0,4th,3th,NaN,NaN,...,1.0,0.0,02.06.2025 11:59:45,980.0,35.0,4.0,"9 min, 35 sec",0,0.0,0.183673
10,Jupiter,02.06.2025,02.06.2025 - Jupiter.txt,11,846,0,1th,3th,NaN,NaN,...,1.0,0.0,02.06.2025 11:59:45,980.0,35.0,4.0,"9 min, 35 sec",0,0.0,0.204082
11,Jupiter,02.06.2025,02.06.2025 - Jupiter.txt,12,760,0,3th,2th,NaN,NaN,...,1.0,0.0,02.06.2025 11:59:45,980.0,35.0,4.0,"9 min, 35 sec",0,0.0,0.224490
12,Jupiter,02.06.2025,02.06.2025 - Jupiter.txt,13,892,0,4th,3th,NaN,NaN,...,1.0,0.0,02.06.2025 11:59:45,980.0,35.0,4.0,"9 min, 35 sec",0,0.0,0.244898
13,Jupiter,02.06.2025,02.06.2025 - Jupiter.txt,14,1002,0,3th,2th,NaN,NaN,...,1.0,0.0,02.06.2025 11:59:45,980.0,35.0,4.0,"9 min, 35 sec",0,0.0,0.265306
14,Jupiter,02.06.2025,02.06.2025 - Jupiter.txt,15,807,0,2th,1th,NaN,NaN,...,1.0,0.0,02.06.2025 11:59:45,980.0,35.0,4.0,"9 min, 35 sec",0,0.0,0.285714
15,Jupiter,02.06.2025,02.06.2025 - Jupiter.txt,16,771,1,2th,2th,NaN,NaN,...,1.0,0.0,02.06.2025 11:59:45,980.0,35.0,4.0,"9 min, 35 sec",0,0.0,0.306122
16,Jupiter,02.06.2025,02.06.2025 - Jupiter.txt,17,768,0,4th,1th,NaN,NaN,...,1.0,0.0,02.06.2025 11:59:45,980.0,35.0,4.0,"9 min, 35 sec",0,0.0,0.326531
17,Jupiter,02.06.2025,02.06.2025 - Jupiter.txt,18,647,1,3th,3th,NaN,NaN,...,1.0,0.0,02.06.2025 11:59:45,980.0,35.0,4.0,"9 min, 35 sec",0,0.0,0.346939
18,Jupiter,02.06.2025,02.06.2025 - Jupiter.txt,19,856,0,2th,4th,NaN,NaN,...,1.0,0.0,02.06.2025 11:59:45,980.0,35.0,4.0,"9 min, 35 sec",0,0.0,0.367347
19,Jupiter,02.06.2025,02.06.2025 - Jupiter.txt,20,878,1,3th,3th,NaN,NaN,...,1.0,0.0,02.06.2025 11:59:45,980.0,35.0,4.0,"9 min, 35 sec",0,0.0,0.387755

In [10]:
df_symbols['percent_no_decision'] = (
    df_symbols.groupby(['session_id', 'participant_id'])['chosen_position']
      .transform(lambda x: (x == 'No decision').mean())
)

In [11]:
#df_symbols = df0[df0['colored'].isna()].copy(deep=True)
#df_symbols = df_symbols[df_symbols['file_3_name'].notna()].copy(deep=True)
df_symbols = df_symbols[df_symbols['chosen_position']!='No decision'].copy(deep=True)
#df_symbols.info()
image_filepath_main = '/media/Data5/emnist_rare_ESRGAN_improved/'
file_cols_name = ['file_1_name', 'file_2_name', 'file_3_name', 'file_4_name']
for f in file_cols_name:
  df_symbols[f] = df_symbols[f].astype(str)
  for index, row in df_symbols.iterrows():
    df_symbols.loc[index, f] = df_symbols.loc[index, f][0] + '/'+df_symbols.loc[index, f][2:] + '_out.png'
print(df_symbols[file_cols_name[0]])

0       y/00902_out.png
1       s/00320_out.png
2       c/01270_out.png
3       f/00745_out.png
4       s/01180_out.png
             ...
6154    f/01252_out.png
6155    m/01187_out.png
6156    m/00439_out.png
6157    m/00413_out.png
6158    c/00117_out.png
Name: file_1_name, Length: 4675, dtype: object

In [12]:
idx=0
for index, row in df_symbols.iterrows():
  df_dataset1.loc[idx, 'x1_omission_percent'] = row['percent_no_decision']
  df_dataset1.loc[idx, 'x2_omission_percent'] = row['percent_no_decision']
  df_dataset1.loc[idx, 'x3_omission_percent'] = row['percent_no_decision']
  df_dataset1.loc[idx, 'x4_omission_percent'] = row['percent_no_decision']
  idx += 1

df_dataset1['x1_omission_percent']

0       0.04
1       0.04
2       0.04
3       0.04
4       0.04
        ...
4670    0.08
4671    0.08
4672    0.08
4673    0.08
4674    0.08
Name: x1_omission_percent, Length: 4675, dtype: object

In [13]:
for index, row in df_symbols.iterrows():
  for f in file_cols_name:
    df_symbols.loc[index, f] = image_filepath_main + df_symbols.loc[index, f]

In [14]:
df_symbols.head(8)

,participant_id,date,original_filename,trial_number,reaction_time,correct,correct_position,chosen_position,prompt,sample_name,...,juice_quantity,datetime,mean_reaction_time,percent_correct,omission_percent,experiment_duration,session_id,session_id_norm,trial_norm,percent_no_decision
0,Jupiter,02.06.2025,02.06.2025 - Jupiter.txt,1,1029,0,2th,3th,NaN,NaN,...,0.0,02.06.2025 11:59:45,980.0,35.0,4.0,"9 min, 35 sec",0,0.0,0.000000,0.04
1,Jupiter,02.06.2025,02.06.2025 - Jupiter.txt,2,579,1,2th,2th,NaN,NaN,...,0.0,02.06.2025 11:59:45,980.0,35.0,4.0,"9 min, 35 sec",0,0.0,0.020408,0.04
2,Jupiter,02.06.2025,02.06.2025 - Jupiter.txt,3,688,0,3th,4th,NaN,NaN,...,0.0,02.06.2025 11:59:45,980.0,35.0,4.0,"9 min, 35 sec",0,0.0,0.040816,0.04
3,Jupiter,02.06.2025,02.06.2025 - Jupiter.txt,4,578,0,4th,2th,NaN,NaN,...,0.0,02.06.2025 11:59:45,980.0,35.0,4.0,"9 min, 35 sec",0,0.0,0.061224,0.04
4,Jupiter,02.06.2025,02.06.2025 - Jupiter.txt,5,848,1,4th,4th,NaN,NaN,...,0.0,02.06.2025 11:59:45,980.0,35.0,4.0,"9 min, 35 sec",0,0.0,0.081633,0.04
5,Jupiter,02.06.2025,02.06.2025 - Jupiter.txt,6,793,1,1th,1th,NaN,NaN,...,0.0,02.06.2025 11:59:45,980.0,35.0,4.0,"9 min, 35 sec",0,0.0,0.102041,0.04
6,Jupiter,02.06.2025,02.06.2025 - Jupiter.txt,7,628,1,1th,1th,NaN,NaN,...,0.0,02.06.2025 11:59:45,980.0,35.0,4.0,"9 min, 35 sec",0,0.0,0.122449,0.04
7,Jupiter,02.06.2025,02.06.2025 - Jupiter.txt,8,771,0,2th,4th,NaN,NaN,...,0.0,02.06.2025 11:59:45,980.0,35.0,4.0,"9 min, 35 sec",0,0.0,0.142857,0.04

In [15]:
df_files = df_symbols[file_cols_name].copy(deep = True)
df_files.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4675 entries, 0 to 6158
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   file_1_name  4675 non-null   object
 1   file_2_name  4675 non-null   object
 2   file_3_name  4675 non-null   object
 3   file_4_name  4675 non-null   object
dtypes: object(4)
memory usage: 311.7+ KB

In [16]:
for index, row in df_symbols.iterrows():
  x1_location = row['chosen_position'][0]
  x234_files = []
  for f in file_cols_name:
    if x1_location in f:
      df_files.loc[index, 'file_1_name']=row[f]
    else:
      x234_files.append(row[f])
  df_files.loc[index, 'file_2_name'] = x234_files[0]
  df_files.loc[index, 'file_3_name'] = x234_files[1]
  df_files.loc[index, 'file_4_name'] = x234_files[2]

In [17]:
df_files.head(8)

,file_1_name,file_2_name,file_3_name,file_4_name
0,/media/Data5/emnist_rare_ESRGAN_improved/f/015...,/media/Data5/emnist_rare_ESRGAN_improved/y/009...,/media/Data5/emnist_rare_ESRGAN_improved/c/008...,/media/Data5/emnist_rare_ESRGAN_improved/m/002...
1,/media/Data5/emnist_rare_ESRGAN_improved/f/017...,/media/Data5/emnist_rare_ESRGAN_improved/s/003...,/media/Data5/emnist_rare_ESRGAN_improved/m/017...,/media/Data5/emnist_rare_ESRGAN_improved/j/010...
2,/media/Data5/emnist_rare_ESRGAN_improved/m/009...,/media/Data5/emnist_rare_ESRGAN_improved/c/012...,/media/Data5/emnist_rare_ESRGAN_improved/y/005...,/media/Data5/emnist_rare_ESRGAN_improved/j/014...
3,/media/Data5/emnist_rare_ESRGAN_improved/s/001...,/media/Data5/emnist_rare_ESRGAN_improved/f/007...,/media/Data5/emnist_rare_ESRGAN_improved/m/016...,/media/Data5/emnist_rare_ESRGAN_improved/c/006...
4,/media/Data5/emnist_rare_ESRGAN_improved/m/003...,/media/Data5/emnist_rare_ESRGAN_improved/s/011...,/media/Data5/emnist_rare_ESRGAN_improved/y/004...,/media/Data5/emnist_rare_ESRGAN_improved/j/013...
5,/media/Data5/emnist_rare_ESRGAN_improved/y/004...,/media/Data5/emnist_rare_ESRGAN_improved/s/009...,/media/Data5/emnist_rare_ESRGAN_improved/c/001...,/media/Data5/emnist_rare_ESRGAN_improved/j/013...
6,/media/Data5/emnist_rare_ESRGAN_improved/j/017...,/media/Data5/emnist_rare_ESRGAN_improved/c/017...,/media/Data5/emnist_rare_ESRGAN_improved/f/007...,/media/Data5/emnist_rare_ESRGAN_improved/m/010...
7,/media/Data5/emnist_rare_ESRGAN_improved/c/001...,/media/Data5/emnist_rare_ESRGAN_improved/j/016...,/media/Data5/emnist_rare_ESRGAN_improved/m/012...,/media/Data5/emnist_rare_ESRGAN_improved/f/013...

In [18]:
X = np.load("/content/drive/MyDrive/monkeytype/all_features16.npy")
paths = np.load("/content/drive/MyDrive/monkeytype/all_paths16.npy", allow_pickle=True)

from sklearn.preprocessing import normalize
X = normalize(X)

path_to_vec = {p: X[i] for i, p in enumerate(paths)}

In [19]:
idx=0
for index, row in df_files.iterrows():
  x1_feat_vec = path_to_vec[row['file_1_name']]
  x2_feat_vec = path_to_vec[row['file_2_name']]
  x3_feat_vec = path_to_vec[row['file_3_name']]
  x4_feat_vec = path_to_vec[row['file_4_name']]
  df_dataset1.loc[idx, feature_names_x1] = x1_feat_vec
  df_dataset1.loc[idx, feature_names_x2] = x2_feat_vec
  df_dataset1.loc[idx, feature_names_x3] = x3_feat_vec
  df_dataset1.loc[idx, feature_names_x4] = x4_feat_vec
  idx += 1

df_dataset1[feature_names_x4]

,x4_f0,x4_f1,x4_f2,x4_f3,x4_f4,x4_f5,x4_f6,x4_f7,x4_f8,x4_f9,x4_f10,x4_f11,x4_f12,x4_f13,x4_f14,x4_f15
0,-0.319251,-0.095402,0.278572,0.242286,0.278839,0.076961,0.272947,-0.222436,0.51223,0.087553,0.22408,0.420774,-0.030837,0.155596,-0.098947,0.112965
1,0.423061,0.117741,-0.397262,0.124597,-0.127762,0.685559,0.05781,0.019171,0.052292,-0.020704,0.041262,0.20837,0.219489,0.055822,0.089891,-0.190093
2,0.304378,0.301603,-0.425079,0.149914,-0.372749,0.40394,0.21649,0.03516,0.284102,0.327785,-0.226166,-0.031531,-0.071213,-0.087844,-0.098149,-0.016892
3,0.010192,-0.038355,-0.251771,0.072541,-0.055664,0.408047,0.009543,-0.153148,0.008209,0.55999,0.183943,-0.120318,0.053831,0.228593,0.543988,-0.153577
4,0.192099,0.052404,-0.373784,-0.03743,-0.451651,0.059127,0.110691,0.113109,0.499284,0.281079,-0.255025,-0.076721,0.065249,-0.250592,-0.347019,-0.003855
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4670,-0.190782,0.149111,-0.29912,0.049539,-0.119091,0.3351,0.282043,-0.210554,0.300878,0.499544,0.265102,-0.263195,-0.106813,0.208387,0.252493,0.02959
4671,0.446282,0.306783,0.038591,-0.011116,-0.162698,0.251594,-0.233576,0.101139,-0.076635,-0.160205,0.272617,-0.04838,-0.237539,0.585889,0.139618,0.152197
4672,0.17111,-0.183054,-0.53991,0.1084,-0.081754,-0.175851,0.086194,-0.447795,0.280169,0.085166,0.040325,-0.126355,-0.067816,-0.039373,0.497539,-0.177109
4673,0.420852,0.093622,-0.481902,0.080501,-0.223072,0.611313,-0.135786,0.064371,-0.051622,0.008906,0.224975,0.071348,0.221736,0.010551,0.088166,-0.117737
4674,-0.276691,0.220825,0.083223,-0.277916,0.240858,-0.056516,0.407231,0.026121,-0.114447,-0.078814,0.133106,0.448396,0.111901,0.192856,0.501096,0.154563

In [20]:
idx=0
for index, row in df_symbols.iterrows():
  df_dataset1.loc[idx, 'x1_linspace_session_id'] = row['session_id_norm']
  df_dataset1.loc[idx, 'x2_linspace_session_id'] = row['session_id_norm']
  df_dataset1.loc[idx, 'x3_linspace_session_id'] = row['session_id_norm']
  df_dataset1.loc[idx, 'x4_linspace_session_id'] = row['session_id_norm']
  df_dataset1.loc[idx, 'x1_linspace_within_session'] = row['trial_norm']
  df_dataset1.loc[idx, 'x2_linspace_within_session'] = row['trial_norm']
  df_dataset1.loc[idx, 'x3_linspace_within_session'] = row['trial_norm']
  df_dataset1.loc[idx, 'x4_linspace_within_session'] = row['trial_norm']
  idx += 1

In [21]:
col = "session_id_norm"

print(df_symbols[col].dtype)
print("NaN:", df_symbols[col].isna().sum())
print("+inf:", np.isposinf(df_symbols[col]).sum())
print("-inf:", np.isneginf(df_symbols[col]).sum())
print(df_symbols[col].describe())

float64
NaN: 0
+inf: 0
-inf: 0
count    4675.000000
mean        0.487541
std         0.295325
min         0.000000
25%         0.214286
50%         0.484848
75%         0.750000
max         1.000000
Name: session_id_norm, dtype: float64

In [22]:
df_dataset1['x1_correct_target'] = (
    df_dataset1.filter(like='x1_symbol_').idxmax(axis=1).str[-1] ==
    df_dataset1.filter(like='x1_correct_symbol_').idxmax(axis=1).str[-1]
).astype(int)

df_dataset1['x2_correct_target'] = (
    df_dataset1.filter(like='x2_symbol_').idxmax(axis=1).str[-1] ==
    df_dataset1.filter(like='x2_correct_symbol_').idxmax(axis=1).str[-1]
).astype(int)

df_dataset1['x3_correct_target'] = (
    df_dataset1.filter(like='x3_symbol_').idxmax(axis=1).str[-1] ==
    df_dataset1.filter(like='x3_correct_symbol_').idxmax(axis=1).str[-1]
).astype(int)

df_dataset1['x4_correct_target'] = (
    df_dataset1.filter(like='x4_symbol_').idxmax(axis=1).str[-1] ==
    df_dataset1.filter(like='x4_correct_symbol_').idxmax(axis=1).str[-1]
).astype(int)

In [23]:
df_dataset1.to_csv('/content/drive/MyDrive/monkeytype/mt_dataset_pref4feat16.csv', index=False)